on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy==1.26.3
        python -m pip install pytest==7.1.2
        python -m pip install vtk==9.3.0
        python -m pip install scipy==1.12.0
        python -m pip install coverage

    - name: Run Tests with Coverage
      env:
        PYTHONPATH: src
      run: coverage run -m pytest src/test/

    - name: Generate Coverage Report
      run: coverage xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
